<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <BaseOutputPath></BaseOutputPath>
    <Platforms>x64</Platforms>
    <StartupObject>Wpf.App</StartupObject>
    <AssemblyName>ImgSizer</AssemblyName>
    <RootNamespace>Wpf</RootNamespace>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Authors>Burnside</Authors>
    <Company>Burnside</Company>
  </PropertyGroup>

  <PropertyGroup>
    <OutputPath>$(SolutionDir)bin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <ApplicationIcon>Logo.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Logo.ico" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="CalcBinding" Version="2.5.2" />
    <PackageReference Include="HandyControl" Version="3.5.1" />
    <PackageReference Include="Stylet" Version="1.3.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoreBridge\CoreBridge.vcxproj" />
  </ItemGroup>

</Project>
